# Generated by Django 2.2.3 on 2019-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=20)),
            ],
        ),
    ]
