# Generated by Django 2.2.3 on 2019-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
