# Generated by Django 2.2.3 on 2019-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sigh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigh',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
